import {money,orderEligibility,type Calculation,type Prices,seedPrices} from './pricing';
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
export async function exportQuote(calc:Calculation&{title?:string;configuration?:unknown},prices:Prices,download=true){
 if(!orderEligibility(calc.net,prices).eligible)throw new Error('Минимальный заказ — '+money(orderEligibility(0,prices).minimum)+' с НДС.');
 const [{PDFDocument,rgb},fontkit]=await Promise.all([import('pdf-lib'),import('@pdf-lib/fontkit')]);
 const doc=await PDFDocument.create();doc.registerFontkit(fontkit.default);const font=await doc.embedFont(await fetch('/fonts/quotation.ttf').then(r=>r.arrayBuffer()),{subset:true});
 const ink=rgb(.129,.137,.137),orange=rgb(.929,.459,.255),gray=rgb(.36,.36,.36);let page=doc.addPage([595.28,841.89]),y=790;
 const line=(text:string,size=10,color=ink)=>{const words=text.split(/\s+/);let row='';for(const word of words){if(font.widthOfTextAtSize((row+' '+word).trim(),size)>499){if(y<60){page=doc.addPage([595.28,841.89]);y=790;}page.drawText(row,{x:48,y,size,font,color});y-=size+7;row=word;}else row=(row+' '+word).trim();}if(row){if(y<60){page=doc.addPage([595.28,841.89]);y=790;}page.drawText(row,{x:48,y,size,font,color});y-=size+7;}};
 page.drawRectangle({x:0,y:827,width:595.28,height:15,color:orange});
 try{const img=new Image();img.src='/assets/logo.svg';await img.decode();const canvas=document.createElement('canvas');canvas.width=450;canvas.height=130;canvas.getContext('2d')!.drawImage(img,0,0,450,130);const logo=await doc.embedPng(canvas.toDataURL('image/png'));page.drawImage(logo,{x:48,y:757,width:140,height:40});y=721;}catch{line('StreetArt',26);}
 line('Предварительное коммерческое предложение',18);line(new Date().toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'})+' · версия прайса '+calc.version,9,gray);y-=18;
 line('Заказ: '+calc.order.city,12);const title=(calc as Calculation&{title?:string}).title;if(title)line(title,12);if(title==='Федеральная адресная программа')line('Изделий: '+calc.order.quantity+'; площадь известных строк: '+calc.area+' м²',10);else if(calc.order.material==='letters'||(typeof calc.configuration==='object'&&calc.configuration!==null&&'recipe' in calc.configuration&&calc.configuration.recipe==='letters'))line('Высота буквы: '+calc.order.letterHeight+' см; количество букв: '+calc.order.quantity,10);else if(!title||!['Листовки','Купоны','Визитки','Буклеты','Стикеры','Плакаты'].some(x=>title.includes(x)))line('Размер: '+calc.order.width+' × '+calc.order.height+' м; количество: '+calc.order.quantity+'; площадь: '+calc.area+' м²',10);y-=15;
 for(const l of calc.lines){line(l.name,11);line(l.quantity+' '+l.unit+' × '+money(l.rate)+' = '+money(l.amount)+' без НДС',9,gray);y-=6;}
 y-=12;line('Стоимость без НДС: '+money(calc.net),12);line('НДС '+(calc.order.vat?Math.round(prices.vatRate*100)+'%':'не включён')+': '+money(calc.vat),11);line((calc.from?'Итого от ':'Итого ')+money(calc.total),20);y-=16;
 line('Предварительный расчёт известных работ. Итоговая цена подтверждается после проверки задания и макета.',10,gray);
 for(const w of calc.warnings)line('• '+w,9,gray);
 line('Минимальный заказ: '+money(orderEligibility(0,prices).minimum)+' с НДС.',9,gray);
 line('Условия, доставка и сроки согласуются для вашего заказа.',9,gray);
 line(prices.validityDays===null?'[PLACEHOLDER: срок действия цены]':'Цена действует '+prices.validityDays+' дней.',9,gray);
 line('[PLACEHOLDER: юридические реквизиты и утверждённые условия заказа]',9,gray);
 const bytes=await doc.save();const blob=new Blob([new Uint8Array(bytes)],{type:'application/pdf'});if(download)downloadBlob(blob,'StreetArt_KP.pdf');return blob;
}
export async function exportXlsx(calc:Calculation,download=true,prices:Prices=seedPrices){if(!orderEligibility(calc.net,prices).eligible)throw new Error('Минимальная сумма заказа не достигнута.');const XLSX=await import('xlsx');const book=XLSX.utils.book_new();const rows=[['StreetArt — предварительный расчёт'],['Версия прайса',calc.version],['Город',calc.order.city],['Позиция','Количество','Ед.','Цена без НДС','Сумма без НДС'],...calc.lines.map(l=>[l.name,l.quantity,l.unit,l.rate,l.amount]),[],['Без НДС',calc.net],['НДС',calc.vat],['Итого от',calc.total],[],...calc.warnings.map(w=>[w])];const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:62},{wch:18},{wch:12},{wch:22},{wch:24}];XLSX.utils.book_append_sheet(book,ws,'Расчёт');const blob=new Blob([XLSX.write(book,{type:'array',bookType:'xlsx'})],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});if(download)downloadBlob(blob,'StreetArt_KP.xlsx');return blob;}
