import {appliances} from './catalog.mjs';
export function conversion(c){
 const {url,button,icon,escape}=c;
 const applianceIcon=id=>`<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">${id==='washer'?'<rect x="23" y="10" width="54" height="79" rx="3"/><path d="M23 28h54M31 19h13"/><circle cx="65" cy="19" r="3"/><circle cx="50" cy="56" r="20"/><path d="M35 57c10-12 17 10 30-3"/>':id==='dishwasher'?'<rect x="20" y="10" width="60" height="79" rx="3"/><path d="M20 28h60M29 19h12M30 70h40M30 79h40M36 36v23M29 42h14M30 36v8M42 36v8"/><circle cx="59" cy="48" r="12"/><circle cx="59" cy="48" r="7"/>':'<rect x="20" y="10" width="60" height="78" rx="3"/><path d="M20 32h60M29 20h27M35 32v14M59 32v14M27 78h46M34 52h25v13c0 10-25 10-25 0V52Zm25 2h5c10 0 10 13-5 13M67 43v6"/><circle cx="68" cy="20" r="3"/>'}</svg>`;
 const cards=()=>`<div class="appliance-cards">${appliances.map((a,i)=>`<a class="appliance-card appliance-${a.id}" href="${url(a.route)}"><span class="appliance-number">0${i+1} / НАПРАВЛЕНИЕ</span><div class="appliance-drawing">${applianceIcon(a.id)}</div><div><h3>${a.plural}</h3><p>${a.scope}</p><span class="text-link">Симптомы и ремонт ${icon('arrow')}</span></div></a>`).join('')}</div>`;
 const quick=()=>`<section class="quick-start wrap" id="quick-start"><div><span class="eyebrow">Первый шаг — без звонка</span><h2>Что требует внимания?</h2><p>Выберите технику и проявление. Получите рекомендации без телефона.</p></div><form id="quick-form" class="quick-form"><label class="field">Ваша техника<select name="appliance">${appliances.map(a=>`<option value="${a.id}">${a.name}</option>`).join('')}</select></label><label class="field">Что произошло?<select name="symptom" required><option value="">Выберите симптом</option>${appliances[0].services.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></label><button class="button" type="submit">Разобраться ${icon('arrow')}</button><p class="note">Результат сразу. Это предварительная проверка, а не диагноз.</p></form></section>`;
 const pricing=()=>`<section class="section white"><div class="wrap price-explainer"><div><span class="eyebrow">Без загадок в смете</span><h2>Важна полная цена.<br>До начала работ.</h2><p>Сравнивайте одинаковый состав ремонта. Небольшая цифра за одну операцию ещё не говорит о сумме заказа.</p>${button('Проверить свою смету','/estimate/','ghost')}</div><div class="estimate-sheet"><div class="sheet-head"><span>СОСТАВ ВАШЕЙ СМЕТЫ</span>${icon('receipt')}</div>${[['01','Диагностика и выезд','В том числе стоимость при отказе от ремонта'],['02','Работа специалиста','Какие операции нужны и за что вы платите'],['03','Детали и материалы','Наименование, совместимость и стоимость'],['04','Дополнительные условия','Демонтаж, доставка, документы и гарантия']].map(([n,t,d])=>`<div class="sheet-row"><span>${n}</span><div><b>${t}</b><small>${d}</small></div>${icon('check')}</div>`).join('')}<p class="note">Точную сумму определяют после диагностики. Условия нашего сервиса будут опубликованы до открытия записи.</p></div></div></section>`;
 const coverage=()=>`<section class="section"><div class="wrap coverage"><div><span class="eyebrow">Москва · выезд по согласованию</span><h2>Начните со своего района.</h2><p>Выберите округ — он сохранится в форме обращения. Возможность выезда и время подтверждает диспетчер.</p></div><div class="district-links">${c.districts.map(d=>`<a href="${url('/booking/?district='+encodeURIComponent(d))}">${d}${icon('arrow')}</a>`).join('')}</div></div></section>`;
 const reassurance=()=>`<div class="assurance-row wrap"><span>${icon('receipt')}Разбор сметы без телефона</span><span>${icon('shield')}Безопасные первые шаги</span><span>${icon('clock')}Подготовка к визиту</span></div>`;
 const faq=(items)=>`<div class="faq">${items.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div>`;
 async function pages(){for(const a of appliances){await c.write(a.route,a.title,a.intro,`${c.heading(a.title,a.intro)}<section class="wrap appliance-intro"><div class="device-summary">${applianceIcon(a.id)}<div><span class="eyebrow">Точный ремонт / ${a.name}</span><p>${a.scope}</p><div class="actions">${button('Проверить неисправность','/diagnostics/?appliance='+a.id)}${button('Запросить визит','/booking/?appliance='+a.id,'ghost')}</div></div></div><p class="note">Онлайн-помощники доступны. Приём обращений откроется после публикации контактов и условий.</p></section><section class="section white"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Узнайте свою ситуацию</span><h2>Что случилось с техникой?</h2></div><p>Выберите проявление. Помощник объяснит возможные направления проверки.</p></div><div class="symptoms">${a.services.map(s=>`<a class="symptom" href="${url('/diagnostics/?appliance='+a.id+'&symptom='+s.id)}"><span class="iconbox">${icon(s.icon)}</span><span><b>${s.name}</b><small>${s.detail}</small></span>${icon('arrow')}</a>`).join('')}</div></div></section><section class="section"><div class="wrap preparation"><div><span class="eyebrow">Подготовка к диагностике</span><h2>Три детали,<br>которые помогут мастеру.</h2><p class="note">${a.modelHint}</p></div><ol>${a.prepare.map(t=>`<li>${t}</li>`).join('')}</ol></div></section><section class="section white"><div class="wrap"><div class="section-head"><h2>Марка и модель имеют значение.</h2><p>Выберите марку, чтобы сохранить её в обращении. Возможность ремонта конкретной модели уточняется до визита.</p></div><div class="brand-links">${a.brands.filter(b=>b!=='Другая').map(b=>`<a href="${url('/booking/?appliance='+a.id+'&brand='+encodeURIComponent(b))}">${escape(b)} ${icon('arrow')}</a>`).join('')}</div><p class="note">Независимый сервис. Упоминание марки не означает авторизацию производителем.</p></div></section>${pricing()}<section class="section"><div class="wrap"><div class="section-head"><h2>До того, как пригласить мастера.</h2></div>${faq([...a.faq,['Сколько будет стоить ремонт?','Сумма зависит от подтверждённой причины, модели, работы и деталей. До согласования уточните также выезд, диагностику при отказе и возможный демонтаж.'],['Как узнать условия гарантии?','Попросите указать срок и предмет гарантии в документах на конкретную работу и деталь. Утверждённые условия нашего сервиса появятся перед открытием приёма.']])}</div></section><section class="section"><div class="wrap">${c.cta()}</div></section>`,'Service',{serviceType:a.title,areaServed:{'@type':'City',name:'Москва'}});}}
 return {cards,quick,pricing,coverage,reassurance,pages};
}
