'use client';
import {useRef,useState} from 'react';
import {Upload,CheckCircle2,AlertTriangle,FileQuestion} from 'lucide-react';
import type {Prices} from '@/lib/pricing';
type Report={name:string;size:number;checks:{status:'ok'|'warn'|'error';text:string}[]};
export function FileCheck({width=6,height=3,prices,onFiles}:{width?:number;height?:number;prices:Prices;onFiles?:(files:{name:string;size:number}[])=>void}){
 const [reports,setReports]=useState<Report[]>([]),[busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
 async function inspect(files:FileList|null){if(!files)return;setBusy(true);const output:Report[]=[];for(const file of [...files].slice(0,10)){const ext=file.name.split('.').pop()?.toLowerCase()||'';const checks:Report['checks']=[];checks.push({status:prices.requirements.formats.includes(ext)?'ok':'error',text:'Формат '+ext.toUpperCase()+(prices.requirements.formats.includes(ext)?' принят для проверки.':' не входит в список макетов.')});if(file.size>2*1024**3){checks.push({status:'error',text:'Файл больше 2 ГБ.'});}else if(file.size>25*1024**2){checks.push({status:'warn',text:'Файл больше 25 МБ: подробная проверка выполняется менеджером.'});}else if(['png','jpg','jpeg'].includes(ext)){try{const image=await createImageBitmap(file);const dpiX=Math.round(image.width/(width*100/2.54)),dpiY=Math.round(image.height/(height*100/2.54));checks.push({status:prices.requirements.minimumDpi===null?'warn':Math.min(dpiX,dpiY)>=prices.requirements.minimumDpi?'ok':'error',text:image.width+' × '+image.height+' px; при '+width+' × '+height+' м: '+dpiX+' × '+dpiY+' dpi.'});image.close();}catch{checks.push({status:'error',text:'Файл не удалось прочитать как изображение.'});}}else if(ext==='pdf'){try{const {PDFDocument}=await import('pdf-lib');const doc=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});const p=doc.getPages()[0];checks.push({status:'ok',text:'PDF читается; страниц: '+doc.getPageCount()+'.'});const w=p.getWidth()*25.4/72,h=p.getHeight()*25.4/72;checks.push({status:Math.abs(w-width*1000)<2&&Math.abs(h-height*1000)<2?'ok':'warn',text:'Размер первой страницы: '+w.toFixed(1)+' × '+h.toFixed(1)+' мм. Требуется '+width*1000+' × '+height*1000+' мм; масштаб согласуйте с менеджером.'});}catch{checks.push({status:'error',text:'PDF не читается или защищён паролем.'});}}else{checks.push({status:'warn',text:'Детальная проверка этого формата выполняется менеджером.'});}
 checks.push({status:'warn',text:'CMYK/RGB, вылеты и шрифты в кривых требуют проверки специалистом.'});if(prices.requirements.minimumDpi===null)checks.push({status:'warn',text:'Минимальное разрешение, вылеты и цветовой профиль уточняются.'});output.push({name:file.name,size:file.size,checks});}
 setReports(output);onFiles?.(output.map(r=>({name:r.name,size:r.size})));setBusy(false);}
 return <div><input ref={input} type="file" multiple hidden onChange={e=>inspect(e.target.files)}/><button type="button" className="upload-zone" disabled={busy} aria-busy={busy} style={{width:'100%'}} onClick={()=>input.current?.click()}><Upload size={25} aria-hidden="true"/><b>{busy?'Проверяем файл…':'Загрузить макет для проверки'}</b><span className="small muted">CDR, PDF, TIFF, JPG, PNG, EPS, AI, PSD, SVG</span><span className="small muted">Проверка в браузере. Файл остаётся на вашем устройстве.</span></button>{reports.map((r,i)=><div className="file-result" role="status" key={i}><b>{r.name}</b><small className="muted">{(r.size/1024**2).toFixed(1)} МБ</small><div className="file-checks">{r.checks.map((c,i)=><div key={i} className={'check-state status-'+c.status}>{c.status==='ok'?<CheckCircle2 size={16} aria-hidden="true"/>:c.status==='error'?<FileQuestion size={16} aria-hidden="true"/>:<AlertTriangle size={16} aria-hidden="true"/>}<span>{c.text}</span></div>)}</div></div>)}</div>;
}
