'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Bookmark,Download,RotateCcw,Upload} from 'lucide-react';
import {toast} from 'sonner';
import {readProjects,removeProject,type LocalProject} from '@/lib/local-workspace';
import {usePrices,setLocalPrices,resetLocalPrices,localPriceOverride} from '@/lib/use-prices';
import {downloadBlob} from '@/lib/exports';
export function LocalProjects(){const [projects,setProjects]=useState<LocalProject[]>([]),[override,setOverride]=useState(false);const {prices}=usePrices();const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{const refresh=()=>{setProjects(readProjects());setOverride(!!localPriceOverride());};refresh();window.addEventListener('streetart-projects',refresh);window.addEventListener('streetart-prices',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('streetart-projects',refresh);window.removeEventListener('streetart-prices',refresh);window.removeEventListener('storage',refresh);};},[]);
 async function importPrices(f?:File){if(!f)return;try{if(f.size>2*1024**2)throw Error('Файл больше 2 МБ');setLocalPrices(JSON.parse(await f.text()));toast.success('Прайс применён на этом устройстве');}catch{toast.error('Не удалось применить прайс. Проверьте структуру JSON и числовые тарифы.');}if(file.current)file.current.value='';}
 return <><div className="workspace-head"><span className="tag"><Bookmark size={15}/>На этом устройстве</span><Link className="btn" href="/calculator">Новый расчёт</Link><Link className="btn btn-outline" href="/brief">Новый бриф</Link></div>{projects.length?<div className="projects-list">{projects.map(p=><article key={p.id} className="saved-project"><div><span className="small muted">{p.kind==='brief'?'Бриф':'Расчёт'} · {new Date(p.date).toLocaleDateString('ru-RU',{timeZone:'Europe/Moscow'})}</span><h2>{p.title}</h2></div><div className="project-actions"><Link className="btn btn-outline btn-small" href={p.url||'/calculator'} onClick={()=>{if(p.kind==='brief')try{localStorage.setItem('streetart-brief-v2',JSON.stringify(p.data));}catch{}}}>Продолжить</Link><button className="icon-button" aria-label={'Скачать '+p.title} onClick={()=>downloadBlob(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),'StreetArt_Project.json')}><Download size={18}/></button><button className="text-action" onClick={()=>{try{const undo=removeProject(p.id);toast('Проект удалён',{action:{label:'Отменить',onClick:undo}});}catch{toast.error('Не удалось удалить проект');}}}>Удалить</button></div></article>)}</div>:<div className="workspace-empty"><Bookmark size={32}/><h2>Здесь будут ваши проекты</h2><p>Сохраните расчёт или заполните бриф. Параметры будут доступны при следующем посещении с этого устройства.</p><Link href="/calculator" className="btn">Рассчитать заказ</Link></div>}<details className="price-config"><summary>Прайс для расчётов на этом устройстве</summary><p>Экспортируйте JSON, измените тарифы и импортируйте файл. Изменения применяются только в этом браузере. Общий прайс сайта обновляется в исходном проекте.</p><p className="small">Активен: {override?'ваш локальный прайс':'прайс сайта'} · v{prices.version}</p><input type="file" ref={file} hidden accept=".json,application/json" onChange={e=>importPrices(e.target.files?.[0])}/><div className="project-actions"><button className="btn btn-outline btn-small" onClick={()=>downloadBlob(new Blob([JSON.stringify(prices,null,2)],{type:'application/json'}),'StreetArt_Prices.json')}><Download size={16}/>Экспорт JSON</button><button className="btn btn-outline btn-small" onClick={()=>file.current?.click()}><Upload size={16}/>Импорт JSON</button>{override&&<button className="btn btn-outline btn-small" onClick={()=>{resetLocalPrices();toast.success('Восстановлен прайс сайта');}}><RotateCcw size={16}/>Вернуть прайс сайта</button>}</div></details><p className="small muted" style={{marginTop:24}}>Расчёты и брифы хранятся в браузере. Они не являются размещёнными заказами. При очистке данных браузера сохранённые проекты исчезнут; важные параметры скачайте в JSON.</p></>;
}
