'use client';
import Link from 'next/link';
import {useState,useDeferredValue,useEffect,useMemo} from 'react';
import dynamic from 'next/dynamic';
import {Palette,ShieldCheck,Package,FileText,MapPin} from 'lucide-react';
import {usePrices} from '@/lib/use-prices';
import catalog from '@/data/catalog.json';
const products=catalog.products;
import {categories,cases,industries,faq,steps} from '@/data/content';
import {constructions,regions,claims} from '@/lib/production';
import {money} from '@/lib/pricing';
import {MiniCalculator} from './mini-calculator';
import {Picker,Placeholder} from './controls';
import {LeadForm} from './lead-form';
import {MarketingPage} from './marketing-page';
import {marketingPages} from '@/data/marketing';
import type {BlogArticle} from '@/data/blog';
const loading=()=> <div className="loading-panel" role="status">Загружаем инструмент…</div>;
const Calculator=dynamic(()=>import('./calculator').then(m=>m.Calculator),{loading});
const FederalProgram=dynamic(()=>import('./federal-program').then(m=>m.FederalProgram),{loading});
const FileCheck=dynamic(()=>import('./file-check').then(m=>m.FileCheck),{loading});
const ProjectBrief=dynamic(()=>import('./project-brief').then(m=>m.ProjectBrief),{loading});
const Cabinet=dynamic(()=>import('./cabinet').then(m=>m.Cabinet),{loading});
const LocalProjects=dynamic(()=>import('./local-projects').then(m=>m.LocalProjects),{loading});
function Intro({title,text,crumb}:{title:string;text?:string;crumb?:string}){return <div className="container page-intro"><div className="breadcrumbs"><Link href="/">Главная</Link><span>/</span><span>{crumb||title}</span></div><h1>{title}</h1>{text&&<p>{text}</p>}</div>;}
function CaseCard({item}:{item:typeof cases[number]}){return <Link href={'/cases/'+item.slug} className="case-card"><div className="case-date">{item.year} · {item.industry}</div><div className="case-name">{item.name}</div><div className="case-number">{item.volume}<span>{item.amount}</span></div><div className="case-detail"><b>{item.geography}</b><p>{item.period}</p></div></Link>;}
function Steps(){return <div className="steps">{steps.map(([h,p])=><div className="step" key={h}><h3>{h}</h3><p>{p}</p></div>)}</div>;}
function Faq(){return <div className="faq-list">{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>;}
function Quality(){return <div className="quality-list">{[[Palette,'До запуска','Проверяем материалы и макет. Согласуем цветопробу.'],[ShieldCheck,'В процессе','Контролируем операции и фиксируем этапы изготовления.'],[Package,'Перед отгрузкой','Проверяем комплектацию и упаковку. Готовим фотографии отправления.']].map(([Icon,h,p])=>{const I=Icon as typeof Palette;return <div className="guarantee" key={String(h)}><I size={23} aria-hidden="true"/><div><h3>{String(h)}</h3><p>{String(p)}</p></div></div>;})}</div>;}
function CTA({title='Начните с задачи',source='Заявка с сайта'}:{title?:string;source?:string}){return <section className="section cta-section"><div className="container grid-2"><div><h2>{title}</h2><p className="cta-copy">Подготовьте параметры, адреса и макет. Продолжите заявку в кабинете: там сохраняются заказы и история согласований. Работаем с заказами от 15 000 ₽ с НДС.</p><Link href="/brief" className="btn btn-dark" style={{marginTop:26}}>Заполнить подробный бриф </Link></div><LeadForm source={source}/></div></section>;}
function Services(){return <div className="services-list">{categories.map(c=><Link className="service-row" href={'/catalog/'+c.path} key={c.id}><h3>{c.name}</h3><p>{c.description}</p><div className="service-tags">{c.tags.map(t=><span key={t}>{t}</span>)}</div></Link>)}</div>;}
function IndustryGrid(){return <div className="industry-grid">{industries.map(x=><Link href={'/industries/'+x.slug} className="industry-link" key={x.slug}><span>{x.name}</span></Link>)}</div>;}
function typeCategory(recipe:string){return recipe==='poly'?'poly':recipe==='banner'?'wide':'branding';}
function countText(n:number,forms:[string,string,string]){const last=n%10,lastTwo=n%100;return n+' '+forms[lastTwo>=11&&lastTwo<=14?2:last===1?0:last>=2&&last<=4?1:2];}
export function SitePage({route,blogArticles=[]}:{route:string;blogArticles?:BlogArticle[]}){
 const {prices}=usePrices();const [search,setSearch]=useState(''),[category,setCategory]=useState('all'),[industry,setIndustry]=useState('all'),[service,setService]=useState('all'),[geography,setGeography]=useState('all');const query=useDeferredValue(search.trim().toLowerCase());
 const rates=useMemo(()=>new Map([...prices.wide,...prices.interior].map(r=>[r.id,r])),[prices]);
 useEffect(()=>{const q=new URLSearchParams(location.search);setSearch(q.get('search')||'');setCategory(q.get('category')||'all');setIndustry(q.get('industry')||'all');setService(q.get('service')||'all');setGeography(q.get('geography')||'all');},[route]);
 function filter(key:string,value:string){({search:setSearch,category:setCategory,industry:setIndustry,service:setService,geography:setGeography}[key as 'search'|'category'|'industry'|'service'|'geography'])?.(value);const url=new URL(location.href);if(value&&value!=='all')url.searchParams.set(key,value);else url.searchParams.delete(key);history.replaceState(null,'',url);}
 if(marketingPages[route])return <MarketingPage route={route}/>;
 if(!route)return <>
 <section className="premium-hero"><div className="container"><div className="premium-hero-grid"><div className="premium-hero-copy"><div className="hero-context">Печать / Конструкции / Оформление</div><h1>Ваш бренд.<br/>По всей России.</h1><p>Печать, вывески и оформление торговых точек. Один партнёр для локальных задач и федеральных кампаний.</p><p className="hero-minimum">Заказы от {money(prices.minimumOrderTotal)} с НДС</p><div className="hero-actions"><Link className="btn" href="/calculator">Рассчитать проект </Link><Link className="hero-text-link" href="/catalog">Выбрать продукцию </Link></div></div><figure className="premium-hero-visual"><img src="/assets/material-study.webp" width="1536" height="1024" alt="Композиция из бумаги, акрила и рекламной конструкции" fetchPriority="high"/><figcaption>Концептуальная иллюстрация материалов StreetArt</figcaption></figure></div><MiniCalculator/></div></section>
 <nav className="container journey-nav" aria-label="С чего начать"><Link href="/services">Выбрать услугу</Link><Link href="/how-to-order">Как заказать</Link><Link href="/pricing">Из чего складывается цена</Link><Link href="/account?view=new">Создать заявку</Link></nav>
 <div className="container brand-facts"><div><strong>28</strong><span>типов конструкций</span></div><div><strong>334</strong><span>разновидности в каталоге</span></div><div><strong>4</strong><span>логистических хаба</span></div><div><strong>2020</strong><span>год основания StreetArt</span></div></div>
 <section className="section"><div className="container"><div className="section-head"><h2>От печатного листа<br/>до нового фасада</h2><Link href="/catalog" className="link-under small">Весь каталог</Link></div><Services/><div className="catalog-invitation"><p>Световые буквы, вывески, навигация и POS. Найдите конструкцию и выберите её исполнение.</p><Link href="/catalog/structures" className="btn btn-outline">28 типов конструкций </Link></div></div></section>
 <section className="federal-feature"><div className="container banner-content"><div className="banner-main"><h2>Один проект.<br/>Сотни адресов.</h2><p>Каждый город, каждое изделие и каждое отправление в одной смете. Импортируйте таблицу и проверьте стоимость по объектам.</p><Link href="/federal" className="btn">Загрузить адресную программу </Link></div><div className="banner-aside"><div className="big-stat">286</div><p>городов в федеральном проекте</p><small>Исторический результат, 2022 год</small></div></div></section>
 <section className="section"><div className="container"><div className="section-head"><h2>Масштаб в деталях</h2><Link href="/cases" className="link-under small">Смотреть кейсы</Link></div><div className="case-grid premium-cases">{cases.slice(0,3).map(x=><CaseCard key={x.slug} item={x}/>)}</div><p className="small muted" style={{marginTop:20}}>Факты из дополнения к брифу. Клиенты обезличены; детали свежих проектов требуют подтверждения перед внешней публикацией.</p></div></section>
 <section className="section process-section"><div className="container"><div className="section-head"><h2>Задача сложная.<br/>Процесс понятный.</h2><p>Партнёрская производственная сеть, единое задание и контроль на каждом этапе.</p></div><Steps/></div></section>
 <section className="section"><div className="container assurance-layout"><div><h2>Качество начинается<br/>до печати</h2><figure><img src="/assets/color-proof.webp" width="811" height="465" alt="Сверка цвета на печатном образце" loading="lazy"/><figcaption>Иллюстрация цветопробы из материалов StreetArt</figcaption></figure></div><Quality/></div></section>
 <section className="section industry-section"><div className="container"><div className="section-head"><h2>Для вашей отрасли</h2></div><IndustryGrid/></div></section>{blogArticles.length>0&&<section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Журнал StreetArt</p><h2>Детали, которые влияют<br/>на результат</h2></div><Link href="/blog" className="btn btn-outline">Все статьи</Link></div><div className="blog-grid">{blogArticles.slice(0,3).map(p=><Link className="blog-card" href={"/blog/"+p.slug} key={p.slug}><span className="eyebrow">{p.category}</span><h3>{p.title}</h3><p>{p.excerpt}</p><span className="link-under">Читать статью</span></Link>)}</div></div></section>}<CTA/>
 <section className="section"><div className="container faq-layout"><div><h2>Перед заказом</h2><Link className="btn btn-outline" href="/calculator?mode=quiz">Подобрать материал</Link></div><Faq/></div></section>
 {claims.claims.filter(c=>c.approved).length>0&&<div className="container approved-claims">{claims.claims.filter(c=>c.approved).map(c=><p key={c.id}>{c.text}</p>)}</div>}
 </>;
 if(route==='calculator')return <><Intro title="Рассчитайте ваш заказ" text="Печать, конструкции и тиражи. Сохраните расчёт, подготовьте смету и бриф. Минимальный заказ — 15 000 ₽ с НДС."/><div className="container"><Calculator/></div></>;
 if(route==='brief')return <><Intro title="Бриф вашего проекта" text="Изделие, объект и документы. Соберите задачу по шагам и сохраните готовый бриф."/><div className="container"><ProjectBrief/></div></>;
 if(route==='account')return <Cabinet/>;
 if(route==='projects')return <><Intro title="Мои проекты" text="Сохранённые расчёты и брифы. Продолжите работу с параметрами предыдущего проекта."/><div className="container"><LocalProjects/></div></>;
 const type=constructions.types.find(t=>route==='catalog/structures/'+t.id);if(type)return <><Intro title={type.name} text={countText(type.count,['разновидность','разновидности','разновидностей'])+'. Выберите исполнение и проверьте состав изделия по типовому рецепту.'}/><div className="container"><Calculator key={type.id} constructionId={type.id} initialMode={type.recipe==='poly'?'poly':'constructor'}/></div></>;
 if(route==='catalog'||route==='catalog/structures'||categories.some(c=>route==='catalog/'+c.path)){
 const current=categories.find(c=>route==='catalog/'+c.path),selected=current?.id||category;const onlyTypes=route==='catalog/structures';const shown=products.filter(p=>(selected==='all'||p.category===selected)&&p.name.toLowerCase().includes(query));const types=constructions.types.filter(t=>(selected==='all'||typeCategory(t.recipe)===selected)&&(t.name+' '+t.variants.join(' ')).toLowerCase().includes(query));
 return <><Intro title={current?.name||(onlyTypes?'Каталог конструкций':'Каталог продукции')} text={current?.description||'Печатные материалы и 28 типов рекламных конструкций. Найдите изделие и выберите его исполнение.'}/><section className="section catalog-section"><div className="container"><div className="filter-bar"><label className="field"><span>Найти изделие</span><input className="input-control" type="search" placeholder="Вывеска, баннер, плёнка…" value={search} onChange={e=>filter('search',e.target.value)}/></label>{!current&&<Picker label="Направление" value={category} onChange={v=>filter('category',v)} options={[{id:'all',name:'Все направления'},...categories]}/>}<span className="small muted" role="status">{countText(types.length,['тип','типа','типов'])}{!onlyTypes?' · '+countText(shown.length,['продукт','продукта','продуктов']):''}</span></div>{types.length>0&&<><div className="catalog-subhead"><h2>Конструкции и оформление</h2><span className="small muted">{countText(types.reduce((s,t)=>s+t.count,0),['разновидность','разновидности','разновидностей'])}</span></div><div className="construction-grid">{types.map(t=><Link href={'/catalog/structures/'+t.id} key={t.id} className="construction-row"><div><h3>{t.name}</h3><p>{t.variants.slice(0,2).join(' · ')}</p></div><span>{countText(t.count,['вариант','варианта','вариантов'])}</span></Link>)}</div></>}{!onlyTypes&&shown.length>0&&<><div className="catalog-subhead"><h2>Печатные материалы и изделия</h2></div><div className="catalog-grid">{shown.map(p=>{const r=p.rateId?rates.get(p.rateId):undefined;return <Link href={'/catalog/'+p.slug} key={p.slug} className="product-card"><span className="small muted">{categories.find(c=>c.id===p.category)?.name}</span><h3>{p.name}</h3><div className="product-price">{r?'от '+money(r.price*(1+prices.vatRate)):'По запросу'}{r&&<span className="small muted"> / {r.unit}</span>}</div><span className="small muted">{r?'Предварительно · с НДС '+Math.round(prices.vatRate*100)+'%':'Формат, бумага и тираж'}</span></Link>;})}</div></>}{!types.length&&(onlyTypes||!shown.length)&&<div className="empty-message">По вашему запросу ничего не найдено.<button className="btn btn-outline" onClick={()=>{filter('search','');filter('category','all');}}>Сбросить фильтры</button></div>}<div className="catalog-invitation"><p>Дизайн, замеры, согласование, монтаж и демонтаж, хранение, утилизация и доставка по адресам.</p><Link className="btn btn-outline" href="/brief">Подготовить задание</Link></div></div></section></>;
 }
 const product=products.find(p=>route==='catalog/'+p.slug);if(product){const r=product.rateId?rates.get(product.rateId):undefined;return <><Intro title={product.name} text={r?'Тариф от '+money(r.price*(1+prices.vatRate))+' за '+r.unit+' с НДС '+Math.round(prices.vatRate*100)+'%. Состав заказа и итоговая стоимость требуют подтверждения.':'Выберите формат, бумагу и тираж. Если тарифа нет, подготовьте бриф для индивидуального расчёта.'}/><div className="container"><Calculator key={product.slug} materialId={product.rateId||undefined} initialMode={product.mode} productName={product.name}/></div><section className="section"><div className="container"><Quality/><div className="article product-guide"><h2>Что согласовать для заказа</h2><p>{product.name}: укажите место размещения, размер готового изделия, количество и дату получения. Для точного расчёта приложите макет или описание задачи.</p><h3>Состав изготовления</h3><p>Материал, способ печати, обработка краёв и крепления зависят от условий эксплуатации. Доставка, установка и подготовка макета согласуются отдельными позициями.</p><h3>До запуска в работу</h3><p>Проверьте размеры и тираж в смете, утвердите макет и условия передачи заказа. Технические характеристики и документы на выбранный материал запрашиваются для конкретного проекта.</p><div className="editorial-actions"><Link className="btn" href="/account?view=new">Создать заявку</Link><Link className="link-under" href="/requirements">Подготовить макет</Link><Link className="link-under" href="/quality">Контроль качества</Link></div></div></div></section></>;}
 if(route==='cases'){const shown=cases.filter(c=>(industry==='all'||c.industry===industry)&&(service==='all'||c.service===service)&&(geography==='all'||c.geography===geography));return <><Intro title="Кейсы в цифрах" text="Тиражи, конструкции и адресные программы. Архивные проекты и факты из дополнения 2024–2026 годов."/><section className="section catalog-section"><div className="container"><div className="filter-bar">{[['industry','Отрасль',industry],['service','Услуга',service],['geography','География',geography]].map(([key,label,value])=><Picker key={key} label={label} value={value} onChange={v=>filter(key,v)} options={[{id:'all',name:'Все'},...[...new Set(cases.map(c=>c[key as 'industry'|'service'|'geography']))].map(name=>({id:name,name}))]}/>)}</div><div className="case-grid">{shown.map(c=><CaseCard key={c.slug} item={c}/>)}</div>{!shown.length&&<p className="empty-message">Нет кейсов с такими параметрами. Измените фильтры.</p>}<p className="notice">Клиенты обезличены. Свежие факты из брифа требуют сверки, фотографии и письменные согласия ещё не предоставлены.</p></div></section><CTA source="Кейсы"/></>;}
 const caseItem=cases.find(c=>route==='cases/'+c.slug);if(caseItem)return <><Intro title={caseItem.name} text={caseItem.extra}/><section className="section catalog-section"><div className="container"><div className="case-full-stats"><div><strong>{caseItem.volume}</strong><p>{caseItem.amount}</p></div><div><strong>{caseItem.geography}</strong><p>География проекта</p></div><div><strong>{caseItem.period}</strong><p>Период и логистика</p></div></div><p className="notice">Источник: {caseItem.source}. {caseItem.review?'Детали проекта требуют проверки перед внешней публикацией.':'Показатели относятся к этому историческому проекту.'}</p><div className="article product-guide"><h2>Планируете похожую задачу?</h2><p>Подготовьте перечень изделий, адреса и даты запуска. Для повторяемых точек опишите типовую комплектацию и отдельно отметьте исключения: размеры, режим доступа, крепления и требования к упаковке.</p><Link className="link-under" href="/downloads">Скачать шаблоны задания</Link></div><Steps/></div></section><CTA title="Подготовьте похожий проект" source={'Кейс '+caseItem.name}/></>;
 if(route==='federal')return <><Intro title="Ваша кампания. Вся Россия." text="Единая адресная программа. Изделия, города и отправления учитываются отдельно."/><div className="container"><FederalProgram prices={prices}/></div><section className="section"><div className="container"><div className="section-head"><h2>От программы<br/>до фотоотчёта</h2></div><Steps/></div></section><CTA source="Федеральная программа"/></>;
 if(route==='industries')return <><Intro title="Решения по отраслям" text="Печать, конструкции и логистика под задачи вашей компании."/><section className="section catalog-section"><div className="container"><IndustryGrid/></div></section>{blogArticles.length>0&&<section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Журнал StreetArt</p><h2>Детали, которые влияют<br/>на результат</h2></div><Link href="/blog" className="btn btn-outline">Все статьи</Link></div><div className="blog-grid">{blogArticles.slice(0,3).map(p=><Link className="blog-card" href={"/blog/"+p.slug} key={p.slug}><span className="eyebrow">{p.category}</span><h3>{p.title}</h3><p>{p.excerpt}</p><span className="link-under">Читать статью</span></Link>)}</div></div></section>}<CTA/></>;
 const vertical=industries.find(i=>route==='industries/'+i.slug);if(vertical)return <><Intro title={vertical.name} text={vertical.task}/><section className="section catalog-section"><div className="container"><div className="industry-services">{vertical.services.map(name=><div key={name}><h2>{name}</h2><Link href={/монтаж|замер/i.test(name)?'/services/installation':/дизайн|макет/i.test(name)?'/services/design':/витрин|плёнк/i.test(name)?'/services/windows':/полиграф|буклет|листов/i.test(name)?'/services/polygraphy':'/services'} className="link-under">Подробнее об услуге</Link></div>)}</div><Quality/></div></section><CTA source={vertical.name}/></>;
 if(route==='about')return <><Intro title="Масштаб с вниманием к деталям" text="StreetArt объединяет печать, конструкции и оформление через партнёрскую производственную сеть."/><section className="section catalog-section"><div className="container about-layout"><article className="article"><h2>Одна задача. Единый партнёр.</h2><p>Подбираем материалы и производство, готовим смету, контролируем изготовление, комплектацию и размещение. Сеть партнёров позволяет работать с региональными и федеральными программами.</p><h2>StreetArt с 2020 года</h2><p>Бренд основан 28 июля 2020 года. Основатель и собственник: Андрей Показаньев. ООО «Юниленд» зарегистрировано в 2016 году.</p><h2>Контроль качества</h2><p>Входной контроль материалов, согласование цветопробы, проверка операций, фото этапов и отгрузки, контроль комплектации. Работа с рекламациями и перепечатка дефектов по согласованным условиям.</p></article><aside className="about-facts"><div><strong>28 / 334</strong><p>типов / разновидностей конструкций</p></div><div><strong>4 хаба</strong><p>Екатеринбург, Москва, Санкт-Петербург, Пермь</p></div><div><strong>286 городов</strong><p>География исторического проекта 2022 года</p></div></aside></div></section><CTA/></>;
 if(route==='delivery')return <><Intro title="Логистика вашего проекта" text="В офис, на склад или по адресам торговых точек. Способ доставки выбирается по габаритам, весу и срокам."/><section className="section catalog-section"><div className="container"><div className="hub-list">{regions.hubs.map(city=><div key={city}><MapPin size={20}/><h2>{city}</h2><span className="small muted">Логистический хаб</span></div>)}</div><div className="article"><h2>Что нужно для расчёта</h2><p>Город и адрес, габариты упаковки, вес, число отправлений и срок получения. Для материалов в рулонах не назначаем грузовой транспорт только из-за площади печати. Для жёстких листов с большей стороной свыше 2,5 м требуется оценка грузового транспорта.</p><p>Вес отправления от 500 кг и сложнодоступные направления рассчитываются индивидуально. Тариф доставки не включён в онлайн-смету.</p><Link href="/federal" className="btn">Проверить адресную программу</Link></div><Placeholder>Полный справочник 1 218 городов / 85 субъектов, подтверждённые тарифы и сроки доставки не приложены к дополнению</Placeholder></div></section><CTA source="Доставка"/></>;
 if(route==='tenders')return <><Intro title="Тендеры и закупки" text="Изделия, материалы и операции в понятной смете. Подготовьте техническое задание и адресную программу."/><section className="section catalog-section"><div className="container grid-2"><div className="article"><h2>Состав предложения</h2><p>Тип конструкции, материалы, тираж, обработка, логистика, монтаж и условия на объекте. Каталог включает 28 типов и 334 разновидности из тендерной номенклатуры.</p><p>Документооборот через СБИС и Диадок согласуется с менеджером. На сайте можно подготовить задание и предварительную смету.</p><Placeholder>Юридический пакет, утверждённые условия закупок и обезличенный пример предложения</Placeholder><Link href="/brief" className="btn">Подготовить техническое задание</Link></div><div className="calc-panel"><h2>Запрос предложения</h2><p className="panel-copy">Канал из брифа: tender@s3t.art. Актуальность контакта требует подтверждения.</p><LeadForm source="Тендеры и закупки"/></div></div></section></>;
 if(route==='contacts')return <><Intro title="Обсудим ваш проект" text="Начните с параметров заказа, макета и адресов. Сохраните задание для согласования."/><section className="section catalog-section"><div className="container grid-2"><div className="contact-card"><h2>Контакты StreetArt</h2><a href="tel:88003023991">8 (800) 302-39-91</a><a href="mailto:hello@str-art.ru">hello@str-art.ru</a><p>Екатеринбург<br/>ул. Луначарского 240, к. 1</p><p className="small muted">Телефон, почта и адрес из материалов сайта 2022 года. Актуальность уточняется.</p><Link className="btn btn-outline" href="/brief">Заполнить бриф</Link></div><div className="calc-panel"><h2>Коротко о задаче</h2><div style={{marginTop:24}}><LeadForm source="Контакты"/></div></div></div></section></>;
 if(route==='requirements')return <><Intro title="Проверим макет до печати" text="Файл проверяется в браузере. Доступные параметры и вопросы для допечатной проверки видны сразу."/><section className="section catalog-section"><div className="container grid-2"><div className="calc-panel"><h2>Проверка файла</h2><p className="panel-copy">Для проверки DPI укажите размер заказа в калькуляторе. Здесь используется размер 6 × 3 м.</p><FileCheck prices={prices}/></div><article className="article"><h2>Перед согласованием</h2><p>Размер готового изделия, масштаб макета, разрешение изображений, цветовой профиль, вылеты и шрифты. Автоматическая проверка не подтверждает параметры, которые невозможно прочитать в браузере.</p><p>Передавайте исходник и файл для просмотра. Назовите файлы по изделию, адресу и версии. Профиль, вылеты и допустимое разрешение подтвердите для выбранной технологии до экспорта.</p><p><Link className="link-under" href="/blog/maket-pered-pechatyu">Чек-лист подготовки макета</Link></p><Link href="/calculator" className="btn">Указать размер заказа</Link></article></div></section></>;
 const articles=[['banner','Как выбрать баннер для улицы'],['artwork','Что проверить в макете'],['federal','Как запустить кампанию в нескольких городах'],['fire','Огнестойкие материалы Г1']];
 if(route==='knowledge')return <><Intro title="Полезное перед заказом" text="Материалы, макеты и адресные программы."/><section className="section catalog-section"><div className="container knowledge-list">{articles.map(([id,title])=><Link href={'/knowledge/'+id} key={id}><FileText size={24}/><h2>{title}</h2></Link>)}</div></section></>;
 if(route.startsWith('knowledge/')){const id=route.split('/')[1];const copy:Record<string,string>={banner:'Начните с места размещения, размера, срока кампании и крепления. Сравните ламинированный и литой баннер по размерам заказа. Условия эксплуатации и материал окончательно согласуются с менеджером.',artwork:'Сверьте размер, масштаб, разрешение изображений, профиль, вылеты и шрифты. Проверка файла показывает только доступные браузеру параметры. До изготовления согласуйте результат допечатной проверки и цветопробу.',federal:'Соберите таблицу с городом, адресом, размером, материалом, количеством и монтажом. Изделия на один адрес группируются в отправление. Исправьте ошибки строк, согласуйте комплектацию, логистику и график.',fire:'Для материала Г1 необходимо проверить действующий сертификат и требования конкретного объекта. Сведения прайса не заменяют документы на выбранный материал.'};return <><Intro title={articles.find(a=>a[0]===id)?.[1]||'База знаний'}/><section className="section catalog-section"><div className="container article"><p>{copy[id]}</p><h2>Зафиксируйте решение в задании</h2><p>Укажите материал, габариты, количество и условия использования. Если есть особые требования объекта, приложите их к заказу. Согласуйте доступные документы и итоговую спецификацию до изготовления.</p><p><Link href="/blog" className="link-under">Практические статьи о подготовке заказа</Link></p><Link href={id==='artwork'?'/requirements':id==='federal'?'/federal':'/calculator'} className="btn">{id==='artwork'?'Проверить файл':'Рассчитать заказ'}</Link><div style={{marginTop:48}}><Faq/></div></div></section></>;}
 if(route==='privacy'||route==='offer')return <><Intro title={route==='privacy'?'Обработка персональных данных':'Условия заказа'}/><section className="section catalog-section"><div className="container article"><p>Приватная версия для проверки сайта. Расчёты, брифы, макеты и адресные программы обрабатываются на устройстве. Формы создают скачиваемый черновик заявки.</p>{route==='offer'&&<p>Минимальный заказ — 15 000 ₽ с НДС. Можно объединить несколько изделий и адресов в один проект. Предварительный расчёт требует подтверждения состава, доставки и условий работ.</p>}<p>Браузер сохраняет тему оформления, проекты, черновик брифа и локальный прайс. При очистке данных браузера они удаляются. Внешняя аналитика и передача данных в CRM не используются.</p><Placeholder>{route==='privacy'?'Утверждённая политика, реквизиты оператора и условия обработки для будущего запуска':'Утверждённые условия заказа, реквизиты, порядок оплаты и срок действия цены'}</Placeholder></div></section></>;
 return <><Intro title="Страница не найдена"/><div className="container section"><Link href="/catalog" className="btn">Перейти в каталог</Link></div></>;
}
