import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
import {renderToStaticMarkup} from 'react-dom/server';
const dir=path.resolve('.sites-runtime/validation');await fs.mkdir(dir,{recursive:true});
const catalog=JSON.parse(await fs.readFile('data/catalog.json','utf8')),products=catalog.products;
const regions=JSON.parse(await fs.readFile('data/regions.json','utf8')),claims=JSON.parse(await fs.readFile('data/claims.json','utf8'));
const contentSource=await fs.readFile('data/content.ts','utf8');
await fs.writeFile(path.join(dir,'content.mjs'),ts.transpileModule(contentSource,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
for(const name of ['marketing','blog'])await fs.writeFile(path.join(dir,name+'.mjs'),ts.transpileModule(await fs.readFile('data/'+name+'.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
const {marketingRoutes}=await import(pathToFileURL(path.join(dir,'marketing.mjs')));
const {seedArticles}=await import(pathToFileURL(path.join(dir,'blog.mjs')));
const marketing="import React from 'react';import {marketingPages} from './marketing.mjs';const Link=({children,href,...p})=>React.createElement('a',{href,...p},children);\n"+(await fs.readFile('components/marketing-page.tsx','utf8')).replace(/^import .+$/gm,'');
await fs.writeFile(path.join(dir,'marketing-page.mjs'),ts.transpileModule(marketing,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText);
const source=await fs.readFile('components/site-page.tsx','utf8');
const icons=source.match(/import \{([^}]+)\} from 'lucide-react'/)[1].split(',').map(x=>x.trim());
const body=source.replace(/^import .+$/gm,'').replace(/^const (Calculator|FileCheck|FederalProgram|ProjectBrief|LocalProjects|Cabinet)=dynamic.+$/gm,'').replace(/^const products=catalog.products;$/gm,'');
const prefix=`import {marketingPages} from './marketing.mjs';import {MarketingPage} from './marketing-page.mjs';import React from 'react';\nimport {categories,cases,clients,industries,faq,steps} from './content.mjs';\nimport {money,seedPrices} from './pricing.mjs';\nconst products=${JSON.stringify(products)},constructions=${JSON.stringify(catalog)},regions=${JSON.stringify(regions)},claims=${JSON.stringify(claims)};\nconst useState=v=>[v,()=>{}],useEffect=()=>{},useDeferredValue=v=>v,useMemo=fn=>fn(),usePrices=()=>({prices:seedPrices,priceError:false});\nconst Link=({children,href,...p})=>React.createElement('a',{href,...p},children);\nconst Placeholder=({children})=>React.createElement('p',null,'[PLACEHOLDER: ',children,']');\nconst LeadForm=()=>React.createElement('p',null,'Ваше имя · Телефон или электронная почта · Задача или комментарий. Продолжить в кабинете. После входа сохраните заявку.');\nconst Calculator=()=>React.createElement('p',null,'[Общий блок калькулятора — тексты приведены ниже]');\nconst MiniCalculator=()=>React.createElement('p',null,'Рассчитайте печать. Материал · Ширина, м · Высота, м · Тираж, шт. Подробный расчёт. С НДС 22% · без доставки.');\nconst FederalProgram=()=>React.createElement('p',null,'[Общий блок адресной программы — тексты приведены ниже]');\nconst Cabinet=()=>React.createElement('p',null,'Личный кабинет. Вход. Регистрация по почте. Заявки, заказы, сметы, файлы, статусы и оплата.');const ProjectBrief=()=>React.createElement('p',null,'[Общий блок пошагового брифа — тексты приведены ниже]');const LocalProjects=()=>React.createElement('p',null,'[Общий блок локальных проектов — тексты приведены ниже]');const MaterialQuiz=()=>null;const FileCheck=()=>React.createElement('p',null,'Загрузить макет для проверки. PDF, TIFF, JPG, PNG, EPS, AI, PSD, SVG. Проверка в браузере. Файл остаётся на вашем устройстве.');\nconst Picker=({label,options})=>React.createElement('p',null,label+': '+options.map(x=>x.name).join(' / '));const PricesSchema={};\n${icons.map(x=>'const '+x+'=()=>null;').join('\n')}\n`;
await fs.writeFile(path.join(dir,'copy-page.mjs'),ts.transpileModule(prefix+body,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText);
const {SitePage}=await import(pathToFileURL(path.join(dir,'copy-page.mjs')));
const {cases,industries,categories}=await import(pathToFileURL(path.join(dir,'content.mjs')));
const routes=[...new Set([...marketingRoutes,'','catalog','calculator','federal','cases','industries','tenders','requirements','about','contacts','delivery','knowledge','privacy','offer','account','projects','brief','catalog/structures',...catalog.types.map(t=>'catalog/structures/'+t.id),...categories.map(c=>'catalog/'+c.path),...products.map(p=>'catalog/'+p.slug),...cases.map(c=>'cases/'+c.slug),...industries.map(c=>'industries/'+c.slug),'knowledge/banner','knowledge/artwork','knowledge/federal','knowledge/fire'])];
const entries=[];for(const route of routes){const html=renderToStaticMarkup(SitePage({route}));const text=html.replace(/<(\/h[123]|\/p|\/div|\/section|\/a|\/summary)[^>]*>/g,'\n').replace(/<br\s*\/?>/g,'\n').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#x27;/g,"'").replace(/&quot;/g,'"').replace(/\s*\n\s*/g,'\n').replace(/ {2,}/g,' ').trim();entries.push('## /'+route+'\n\n'+text);}
function literalCopy(s){const sourceFile=ts.createSourceFile('copy.tsx',s,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);const set=new Set();function walk(n){if(ts.isJsxText(n)){const t=n.text.replace(/\s+/g,' ').trim();if(/[А-Яа-яЁё]/.test(t))set.add(t);}else if(ts.isStringLiteral(n)&&/[А-Яа-яЁё]/.test(n.text)&&n.text.length>3)set.add(n.text);ts.forEachChild(n,walk);}walk(sourceFile);return [...set].join('\n\n');}
entries.push('## /blog\n\nЖурнал StreetArt. Поиск и фильтрация статей по темам.');for(const a of seedArticles)entries.push('## /blog/'+a.slug+'\n\n'+a.title+'\n\n'+a.excerpt+'\n\n'+a.body);
let out='# Тексты всех страниц StreetArt\n\nРедакция от 06.10.2026, минимальный заказ 15 000 ₽ с НДС. Тексты страниц получены из фактических шаблонов сайта. Общие интерфейсные блоки приведены один раз после страниц. Цена зависит от параметров; источником остаётся data/prices.json.\n\n'+entries.join('\n\n');
for(const [name,file] of [['Редактор блога','components/blog-editor.tsx'],['Личный кабинет','components/cabinet.tsx'],['Калькулятор','components/calculator.tsx'],['Расчёт по площади','components/print-calculator.tsx'],['Пошаговый бриф','components/project-brief.tsx'],['Локальные проекты','components/local-projects.tsx'],['Форма черновика заявки','components/lead-form.tsx'],['Мини-калькулятор','components/mini-calculator.tsx'],['Адресная программа','components/federal-program.tsx'],['Подбор материала','components/material-quiz.tsx'],['Проверка макета','components/file-check.tsx'],['Общие формы и навигация','components/shell.tsx']])out+='\n\n## Общий блок: '+name+'\n\n'+literalCopy(await fs.readFile(file,'utf8'));
await fs.writeFile('COPY.md',out.replace(/[ \t]+$/gm,''));await fs.writeFile('reports/routes.json',JSON.stringify({defined:routes.length,sourceRenderPassed:routes.length,note:'Шаблоны страниц отрисованы в static markup для проверки текста. Динамические инструменты заменены ссылками на их общие блоки текста. Браузерная проверка этой редакции недоступна; это проверка шаблонов, а не интерактивных сценариев.',routes:[...routes.map(x=>'/'+x),'/blog','/blog/editor',...seedArticles.map(a=>'/blog/'+a.slug)]},null,2));console.log(JSON.stringify({copyPages:routes.length,sourceRenderPassed:routes.length}));
