import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
const dir=path.join(process.cwd(),'.sites-runtime/validation');
const src=(await fs.readFile('lib/exports.ts','utf8')).replace("from './pricing'","from './pricing.mjs'");
await fs.writeFile(path.join(dir,'exports.mjs'),ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
const {calculate,initialOrder,seedPrices}=await import(pathToFileURL(path.join(dir,'pricing.mjs')));
const objectUrls=new Map(),writes=[];
const realFetch=globalThis.fetch;globalThis.fetch=async url=>url==='/fonts/quotation.ttf'?new Response(await fs.readFile('public/fonts/quotation.ttf')):realFetch(url);
globalThis.URL.createObjectURL=blob=>{const id='blob:test-'+objectUrls.size;objectUrls.set(id,blob);return id;};
globalThis.URL.revokeObjectURL=()=>{};
globalThis.document={body:{appendChild(){}},createElement:()=>({style:{},click(){writes.push(objectUrls.get(this.href).arrayBuffer().then(bytes=>fs.writeFile('reports/'+this.download,new Uint8Array(bytes))));},remove(){}})};
const {exportQuote,exportXlsx}=await import(pathToFileURL(path.join(dir,'exports.mjs')));
const quotation=calculate({...initialOrder,quantity:4});
await assert.rejects(exportQuote(calculate(initialOrder),seedPrices),/Минимальный заказ/);
await assert.rejects(exportXlsx(calculate(initialOrder),false,seedPrices),/Минимальная сумма/);
await exportQuote(quotation,seedPrices);await Promise.all(writes);
const excel=await exportXlsx(quotation,false,seedPrices),XLSX=await import('xlsx'),book=XLSX.read(await excel.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1});
assert.equal(rows.find(r=>r[0]==='Итого от')[1],quotation.total);
await fs.writeFile('reports/StreetArt_KP.xlsx',new Uint8Array(await excel.arrayBuffer()));
await fs.writeFile('reports/exports-tests.json',JSON.stringify({passed:4,failed:0,tests:['PDF: запрет КП ниже минимума','Excel: запрет КП ниже минимума','Кириллический PDF из фактической функции','Excel: сумма сохранена в числовой ячейке']},null,2));
console.log('PASS PDF / Excel: minimum policy, actual exports, numeric totals');
