import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import ts from 'typescript';
const root=process.cwd(),dir=path.join(root,'.sites-runtime/validation');await fs.mkdir(dir,{recursive:true});
const raw=await fs.readFile('data/prices.json','utf8');
let source=await fs.readFile('lib/pricing.ts','utf8');source=source.replace("import defaultPrices from '@/data/prices.json';",'const defaultPrices='+raw+';');
await fs.writeFile(path.join(dir,'pricing.mjs'),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
source=await fs.readFile('lib/production.ts','utf8');
for(const [binding,file] of [['recipeData','recipes'],['regionData','regions'],['constructionData','catalog'],['claimData','claims']])source=source.replace(new RegExp("import "+binding+" from '@/data/[^']+';"),'const '+binding+'='+await fs.readFile('data/'+file+'.json','utf8')+';');
source=source.replace("from './pricing'","from './pricing.mjs'");
await fs.writeFile(path.join(dir,'production.mjs'),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
source=await fs.readFile('lib/address-program.ts','utf8');source=source.replace("from './pricing'","from './pricing.mjs'").replace("from './production'","from './production.mjs'");
await fs.writeFile(path.join(dir,'address-program.mjs'),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText);
const {calculate,initialOrder,seedPrices,addVat,PricesSchema,quotePolygraphy}=await import(pathToFileURL(path.join(dir,'pricing.mjs')));
const {calculateProgram,normalizeCity}=await import(pathToFileURL(path.join(dir,'address-program.mjs')));
const passed=[];function test(name,fn){fn();passed.push(name);console.log('PASS '+name);}
test('6×3 м баннер 330: 3 402 без НДС, 748.44 НДС, 4 150.44 итого',()=>{const r=calculate(initialOrder);assert.equal(r.area,18);assert.equal(r.net,3402);assert.equal(r.vat,748.44);assert.equal(r.total,4150.44);});
test('Все 12 медианных тарифов совпадают с исходным конфигом',()=>{for(const p of seedPrices.wide){const r=calculate({...initialOrder,width:1,height:1,material:p.id});assert.equal(r.net,p.price);assert.equal(r.total,Math.round(p.price*122)/100);}});
test('Люверсы, проклейка и количество: 2 изделия 6×3',()=>{const r=calculate({...initialOrder,quantity:2,glue:true,eyelets:8});assert.equal(r.net,9096);assert.equal(r.total,11097.12);assert.equal(r.lines.find(l=>l.name.includes('Проклейка')).quantity,36);});
test('Ламинация 450/м² и резка 111/м²',()=>{const r=calculate({...initialOrder,lamination:'lamination',cut:'cut'});assert.equal(r.net,13500);assert.equal(r.total,16470);});
test('Монтаж баннера 550/м², альпинист 370/м², расходники 500 и вышка 2 969',()=>{const r=calculate({...initialOrder,mount:true,heightWork:true,supplies:'supplies-basic',lift:true});assert.equal(r.net,23431);assert.equal(r.total,28585.82);});
test('Монтаж плёнки Orajet — 600/м², тариф печати 235/м²',()=>{const r=calculate({...initialOrder,material:'orajet',mount:true});assert.equal(r.net,15030);});
test('Вывеска с подсветкой 2×1 — 7 967/м²',()=>{const r=calculate({...initialOrder,mode:'interior',material:'sign-lit',width:2,height:1});assert.equal(r.net,15934);assert.equal(r.total,19439.48);});
test('Объёмные буквы: 30 см × 5 шт × 97/см, площадь не участвует',()=>{const r=calculate({...initialOrder,mode:'interior',material:'letters',letterHeight:30,quantity:5});assert.equal(r.net,14550);assert.equal(r.total,17751);});
test('Roll-up считается по штукам 21 478 × 2',()=>{const r=calculate({...initialOrder,mode:'interior',material:'rollup',quantity:2});assert.equal(r.net,42956);});
test('UV с белилами + ПВХ 3 мм: (600+345) × 2м²',()=>{const r=calculate({...initialOrder,mode:'interior',material:'uv-white',substrate:'pvc-3',width:2,height:1});assert.equal(r.net,1890);});
test('Переключатель НДС исключает налог ровно один раз',()=>{const r=calculate({...initialOrder,vat:false});assert.equal(r.total,3402);assert.equal(r.vat,0);assert.deepEqual(addVat(189,.22,true),{net:189,vat:41.58,total:230.58});});
test('Отсутствующая доставка не объявляется бесплатной',()=>{const r=calculate(initialOrder);assert(r.warnings.some(w=>w.includes('Доставка')));assert(r.from);assert(!r.lines.some(l=>l.group==='delivery'));});
test('Неутверждённая срочность не меняет цену, явно предупреждает',()=>{const r=calculate({...initialOrder,urgency:'overnight'});assert.equal(r.total,4150.44);assert(r.warnings.some(w=>w.includes('Срочность')));});
test('Настроенные доставка, срочность и регион участвуют в расчёте',()=>{const p=structuredClone(seedPrices);p.deliveryRates={'Екатеринбург':100};p.urgencyCoefficients.urgent=1.2;p.regionalCoefficients={'Екатеринбург':1.1};const r=calculate({...initialOrder,urgency:'urgent'},p);assert.equal(r.net,4590.64);});
test('Розничная наценка применяется только ниже явно заданного порога',()=>{const p=structuredClone(seedPrices);p.retail_markup=1.5;p.retail_threshold=20;p.retail_threshold_unit='area';assert.equal(calculate(initialOrder,p).net,5103);assert.equal(calculate({...initialOrder,quantity:2},p).net,6804);});
test('Не выдумывается скидка за большой объём',()=>{const r=calculate({...initialOrder,quantity:1000});assert.equal(r.net,3402000);});
test('Минимальная тарифицируемая площадь считается на изделие, если утверждена',()=>{const p=structuredClone(seedPrices);p.minimumArea=1;const r=calculate({...initialOrder,width:.2,height:.3,quantity:4},p);assert.equal(r.billableArea,4);assert.equal(r.net,756);});
test('Ошибочные размеры, NaN, дробный тираж и неизвестный материал отклоняются',()=>{for(const patch of [{width:0},{height:-1},{quantity:1.5},{width:NaN},{material:'unknown'}])assert.throws(()=>calculate({...initialOrder,...patch}));});
test('100 строк адресной программы считаются без ручной правки',()=>{const rows=Array.from({length:100},(_,i)=>({'город':i%2?'г. Москва':'Екб','адрес':'Тестовый адрес '+i,'размер':'6x3','материал':'banner-330','количество':1,'монтаж':'нет'}));const result=calculateProgram(rows,seedPrices);assert.equal(result.length,100);assert(result.every(x=>x.calculation));assert.equal(result.reduce((s,x)=>s+x.calculation.total,0).toFixed(2),'415044.00');assert.equal(result[0].input.city,'Екатеринбург');});
test('Ошибочная строка адресной программы не включается в итог',()=>{const r=calculateProgram([{'город':'Москва','адрес':'Тест','размер':'6x3','материал':'banner-330'},{'город':'Москва','адрес':'Тест','размер':'ошибка','материал':'banner-330'}],seedPrices);assert(r[0].calculation);assert.equal(r[1].calculation,null);});
test('Полиграфия без матрицы возвращает запрос, без выдуманной цены',()=>{assert.equal(quotePolygraphy({product:'Листовки',format:'А5',paper:'80',color:'4+4',quantity:1000},seedPrices),null);});
test('Схема прайса запрещает отрицательную цену и НДС > 100%',()=>{const p=structuredClone(seedPrices);p.wide[0].price=-1;assert.throws(()=>PricesSchema.parse(p));p.wide[0].price=189;p.vatRate=2;assert.throws(()=>PricesSchema.parse(p));});
const report={date:new Date().toISOString().slice(0,10),passed:passed.length,failed:0,tests:passed};await fs.mkdir('reports',{recursive:true});await fs.writeFile('reports/pricing-tests.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:passed.length,failed:0}));
