import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {SitePage} from '@/components/site-page';
import catalog from '@/data/catalog.json';
const products=catalog.products;
import {categories,cases,industries,faq} from '@/data/content';
import {getPrices} from '@/lib/price-server';
import {constructions} from '@/lib/production';
import {marketingPages} from '@/data/marketing';
const pages:Record<string,string>={catalog:'Каталог услуг',calculator:'Калькулятор стоимости',federal:'Федеральные кампании',cases:'Кейсы',industries:'Решения по отраслям',tenders:'Тендеры и закупки',requirements:'Требования к макетам',about:'О компании',contacts:'Контакты',delivery:'Доставка и география',knowledge:'База знаний',privacy:'Обработка персональных данных',offer:'Условия заказа',account:'Личный кабинет','knowledge/banner':'Как выбрать баннер для улицы','knowledge/artwork':'Что проверить в макете','knowledge/federal':'Как запустить федеральную кампанию','knowledge/fire':'Огнестойкие материалы Г1'};
export function routeTitle(route:string){return ({brief:'Бриф проекта',account:'Личный кабинет',projects:'Черновики на устройстве','catalog/structures':'Каталог конструкций'} as Record<string,string>)[route]||marketingPages[route]?.title||pages[route]||constructions.types.find(t=>route==='catalog/structures/'+t.id)?.name||products.find(p=>route==='catalog/'+p.slug)?.name||categories.find(c=>route==='catalog/'+c.path)?.name||cases.find(c=>route==='cases/'+c.slug)?.name||industries.find(i=>route==='industries/'+i.slug)?.name;}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}):Promise<Metadata>{
 const route=(await params).slug.join('/'),title=routeTitle(route)||'Страница не найдена';
 const product=products.find(p=>route==='catalog/'+p.slug),project=cases.find(c=>route==='cases/'+c.slug),type=constructions.types.find(t=>route==='catalog/structures/'+t.id);
 const description=marketingPages[route]?.intro||(project?`${project.name}: ${project.volume} ${project.amount}. ${project.geography}. Проект StreetArt, ${project.year}.`:product?`${product.name}: параметры, материал и предварительный расчёт StreetArt. Минимальный заказ — 15 000 ₽ с НДС. Подготовьте смету и бриф.`:type?`${type.name}: ${type.variants.length} исполнений в каталоге StreetArt. Выберите конструкцию и подготовьте бриф. Заказы от 15 000 ₽ с НДС.`:`${title} StreetArt. Печать, рекламные конструкции и оформление объектов. Соберите параметры проекта. Минимальный заказ — 15 000 ₽ с НДС.`);
 return {title,description,alternates:{canonical:'/'+route}};
}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const route=(await params).slug.join('/');if(!routeTitle(route))notFound();const product=products.find(p=>route==='catalog/'+p.slug);const prices=await getPrices();const rate=[...prices.wide,...prices.interior].find(p=>p.id===product?.rateId);const data:unknown[]=[{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Главная',item:'https://streetart-print.mossy-seal-0693.chatgpt.site/'},{'@type':'ListItem',position:2,name:routeTitle(route),item:'https://streetart-print.mossy-seal-0693.chatgpt.site/'+route}]}];if(product)data.push({'@context':'https://schema.org','@type':'Product',name:product.name,brand:{'@type':'Brand',name:'StreetArt'},...(rate&&prices.priceApproval?{offers:{'@type':'Offer',price:(rate.price*(1+prices.vatRate)).toFixed(2),priceCurrency:'RUB',availability:'https://schema.org/PreOrder'}}:{})});return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/><SitePage route={route}/></>;}
